const seedData = [
  {
    firstName: 'Sunny',
    lastName: 'Anter',
    morningRoute: 'R5 SABADELL',
    morningStop: 'BARBERÀ DEL VALLÈS Carretera de Barcelona, 280',
    eveningRoute: 'R5 SABADELL',
    eveningStop: 'SABADELL Carretera de Barcelona, 621',
    contactPerson1: 'Sam Polge',
    contactPerson1Phone: '08900849382',
    contactPerson2: 'Gerry',
    contactPerson2Phone: '00849423382',
    address: 'Buckingham Palace (Barcelona)',
    additionalInfo: '',
  },
  {
    firstName: 'Tekraj',
    lastName: 'Gurang',
    morningRoute: 'R2 SANT CUGAT',
    morningStop: 'SANT CUGAT Bergara, 17',
    eveningRoute: 'R5 SABADELL',
    eveningStop: 'SABADELL Rambla Ponent, 45-47',
    contactPerson1: 'Luigi Faldetta',
    contactPerson1Phone: '09876543',
    contactPerson2: null,
    contactPerson2Phone: null,
    address: '',
    additionalInfo: '',
  },
  {
    firstName: 'Jason',
    lastName: 'Wong',
    morningRoute: 'R5 SABADELL',
    morningStop: 'SABADELL Carretera de Barcelona, 621',
    eveningRoute: 'R2 SANT CUGAT',
    eveningStop: 'SANT CUGAT Rotonda Mercantic ',
    contactPerson1: 'Toby Dixon Smith',
    contactPerson1Phone: '123456789',
    contactPerson2: 'Timon Sejbuk',
    contactPerson2Phone: '6574839202',
    address: '59 Horseferry Road, London',
    additionalInfo: '',
  },
];

const newData = {
  firstName: 'Thomas',
  lastName: 'Tank',
  morningRoute: 'London route 1',
  morningStop: 'westminster',
  eveningRoute: 'London route 2',
  eveningStop: 'Victoria',
  contactPerson1: 'Postman Pat',
  contactPerson1Phone: '928374',
  contactPerson2: 'Spongebob',
  contactPerson2Phone: '2345',
  address: 'Big Ben',
  additionalInfo: '',
};

module.exports = { seedData, newData };
